//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class Localization
{
	public static string Score = "Score: ";
	public static string OutOfZone = "Out-of-bounds !";

	public static string Hole = "Hole !";
	public static string Bogey = "Bogey !";
	public static string Par = "Par !";
	public static string Birdie = "Birdie !";
	public static string Eagle = "Eagle !";
	public static string Albatros = "Albatros !";
	public static string Condor = "Condor !";
}

